export const DEFAULT_ACP_CHAT_EVENT_PAGE_SIZE = 96;
export const DEFAULT_ACP_CHAT_EVENT_WINDOW_PAGE_COUNT = 3;
export const DEFAULT_ACP_CHAT_LOADED_EVENT_BUFFER_LIMIT =
  DEFAULT_ACP_CHAT_EVENT_PAGE_SIZE * DEFAULT_ACP_CHAT_EVENT_WINDOW_PAGE_COUNT;
export const ACP_CHAT_LOADED_EVENT_BUFFER_MAX_MULTIPAGE_ITEMS = 1_080;
